#version: '3.8'

services:
  app:
    image: 
    container_name: laravel-app
    hostname: Laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      #- ./php.ini:/usr/local/etc/php/conf.d/custom.ini  # opcional para php config
    ports:
      - "8000:8000"
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  dbdata:
