version: '3.8'

services:
  app:
    image: raulaxxo/laravel:1.2
    container_name: laravel-app
    hostname: Laravel
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laraveluser", "-psecret"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./start-nginx.sh:/start.sh
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: ["/bin/sh", "/start.sh"]
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    depends_on:
      - app
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTHCHECK_URL}"]
      interval: 30s
      timeout: 10s
      retries: 5

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./src:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email tu_email@ejemplo.com --agree-tos --no-eff-email -d ${APP_DOMAIN}
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  dbdata:
  certbot-etc:
  certbot-var:
