name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    #paths:
     # - 'Dockerfile'

jobs:
  call-build-push:
    uses: Raulaxxo/DockerBuildPush/.github/workflows/build-and-push-docker.yml@main
    with:
      image_name: raulaxxo/laravel
      image_version: 1.2
      dockerfile_path: ./Dockerfile
      context_path: .
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

