name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'

jobs:
  call-build-push:
    uses: Raulaxxo/DockerBuildPush/.github/workflows/build-and-push-docker.yml@master
    with:
      image_name: raulaxxo/laravel
      image_tag: 1.3
      dockerfile_path: ./Dockerfile
      context: .
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

